# Klebsiella metadata

In [2]:
import pandas as pd

# Load data
metadata_file = "/home/dca36/rds/rds-floto-bacterial-4k08a2yyQLw/david/final/metadata_final_curated_slimmed.tsv"
metadata = pd.read_csv(metadata_file, sep="\t")
display(metadata.head())

/tmp/ipykernel_1383769/905020374.py:5: DtypeWarning: Columns (0: infB, 1: mlst.sequence_type, 2: metadata.sample.accession, 3: accession, 4: dev_stage, 5: scientific_name, 6: center_name, 7: amr_study, 8: study_setting, 9: poppunk_cluster) have mixed types. Specify dtype option on import or set low_memory=False.
  metadata = pd.read_csv(metadata_file, sep="\t")

,Sample,is_kpsc,kpsc_final_list,is_refseq,is_nctc,species,species_match,Clonal group,LINcode,Phylogroup,...,dev_stage,scientific_name,center_name,amr_study,study_setting,bakta_gbff_downloaded,bakta_gff3_downloaded,assembly_file,gff_file,poppunk_cluster
0,SAMD00002693,False,False,False,False,Klebsiella ornithinolytica,strong,NaN,NaN,NaN,...,NaN,Raoultella ornithinolytica,GIFU_MED,NaN,NaN,False,True,NaN,NaN,NaN
1,SAMD00008836,False,False,False,False,Klebsiella terrigena,strong,NaN,NaN,NaN,...,NaN,Klebsiella pneumoniae subsp. ozaenae,GIFU_MED,NaN,NaN,False,True,NaN,david/raw/klebsiella_gff3/SAMD00008836.bakta.g...,NaN
2,SAMD00008944,False,False,False,False,Klebsiella oxytoca,strong,NaN,NaN,NaN,...,NaN,Klebsiella oxytoca,GIFU_MED,NaN,NaN,False,True,NaN,david/raw/klebsiella_gff3/SAMD00008944.bakta.g...,NaN
3,SAMD00009480,False,False,False,False,Klebsiella aerogenes,strong,NaN,NaN,NaN,...,NaN,Klebsiella aerogenes,GIFU_MED,NaN,NaN,False,True,NaN,david/raw/klebsiella_gff3/SAMD00009480.bakta.g...,NaN
4,SAMD00049595,True,True,False,False,Klebsiella pneumoniae,strong,CG711,0_0_137_11_45_0_0_0_1_0,Kp1,...,NaN,Klebsiella pneumoniae,KYOTO_GM,NaN,NaN,False,True,seb/assemblies_2/klebsiella_pneumoniae__01/SAM...,david/raw/klebsiella_gff3/SAMD00049595.bakta.g...,128

In [3]:
# Check how many gff files are missing
print(f"Number of gff files missing: {metadata['gff_file'].isna().sum()}")
missing_gff_files = metadata[metadata['gff_file'].isna()]
display(missing_gff_files.head())

Number of gff files missing: 1

,Sample,is_kpsc,kpsc_final_list,is_refseq,is_nctc,species,species_match,Clonal group,LINcode,Phylogroup,...,dev_stage,scientific_name,center_name,amr_study,study_setting,bakta_gbff_downloaded,bakta_gff3_downloaded,assembly_file,gff_file,poppunk_cluster
0,SAMD00002693,False,False,False,False,Klebsiella ornithinolytica,strong,NaN,NaN,NaN,...,NaN,Raoultella ornithinolytica,GIFU_MED,NaN,NaN,False,True,NaN,NaN,NaN

In [4]:
# Double check that all with sublineage not null are in kpsc_final_list
sl_samples = metadata[metadata['Sublineage'].notna()]
# Number of samples with sublineage not null
print(f"Number of samples with sublineage not null: {len(sl_samples)}")
# Number of samples with sublineage not null and in kpsc_final_list
sl_samples = sl_samples[sl_samples['kpsc_final_list']]
print(f"Number of samples with sublineage not null and in kpsc_final_list: {len(sl_samples)}")

Number of samples with sublineage not null: 80641
Number of samples with sublineage not null and in kpsc_final_list: 79042

In [3]:
# Check the assembly column completeness - 'assembly_file'
print(f"Number of metadata entries: {len(metadata)}")
print(f"Number of missing assembly files: {metadata['assembly_file'].isna().sum()}")
# Group by species and count, sort by count
missing_assembly_files = metadata[metadata['assembly_file'].isna()]
print(missing_assembly_files['species'].value_counts().head(10))

Number of metadata entries: 88303
Number of missing assembly files: 3148
species
Klebsiella michiganensis      846
Klebsiella aerogenes          684
Klebsiella oxytoca            548
Klebsiella ornithinolytica    458
Klebsiella planticola         215
Klebsiella grimontii          180
Klebsiella terrigena           60
Klebsiella pasteurii           54
Klebsiella Ka4                 35
Klebsiella sauropsida          19
Name: count, dtype: int64

In [6]:
# Filter to those samples in kpsc_final_list True
kpsc_final_list_samples = metadata[metadata['kpsc_final_list']]
print(f"Number of samples in kpsc_final_list: {len(kpsc_final_list_samples)}")

Number of samples in kpsc_final_list: 79450

In [14]:
# The size of the SLs, value counts
# Calculate the total number of samples in sublineages of size < 25
sublineage_counts = kpsc_final_list_samples['Sublineage'].value_counts()
# Print a list of all sl's with size > 100,convert to list so we can print it
print(list(sublineage_counts[sublineage_counts > 500].index))
display(sublineage_counts.head(23))

['SL258', 'SL147', 'SL17', 'SL307', 'SL15', 'SL14', 'SL37', 'SL45', 'SL101', 'SL231', 'SL268', 'SL29', 'SL39', 'SL23', 'SL395', 'SL35', 'SL107', 'SL13', 'SL111', 'SL25', 'SL48', 'SL34', 'SL3010']

Sublineage
SL258     16229
SL147      5096
SL17       4630
SL307      4449
SL15       3647
SL14       2521
SL37       1871
SL45       1803
SL101      1610
SL231      1049
SL268       954
SL29        909
SL39        886
SL23        863
SL395       851
SL35        783
SL107       702
SL13        647
SL111       601
SL25        590
SL48        567
SL34        531
SL3010      502
Name: count, dtype: int64

In [19]:
def run_panaroo_on_small_sublineages(n: int):
    # Calculate the total number of samples in sublineages of size < n
    small_sublineages = sublineage_counts[sublineage_counts < n]
    # Filter to metadata file to only include the SLs of size < n
    small_sublineages_metadata = kpsc_final_list_samples[kpsc_final_list_samples['Sublineage'].isin(small_sublineages.index)]
    print(f"Total number of samples in sublineages of size < {n}: {len(small_sublineages_metadata)}")
    print(f"Total number of sublineages of size < {n}: {len(small_sublineages)}")

    # Save the metadata file to david/processed/panaroo_run/sublineages_size_<n>.tsv
    small_sublineages_metadata.to_csv(f"/home/dca36/rds/rds-floto-bacterial-4k08a2yyQLw/david/processed/panaroo_run/sublineages_smaller_than_{n}.tsv", sep="\t")
    print(f"Saved metadata file to david/processed/panaroo_run/sublineages_smaller_than_{n}.tsv")
    return small_sublineages_metadata

In [21]:
sl_less_than_10 = run_panaroo_on_small_sublineages(10)

Total number of samples in sublineages of size < 10: 5780
Total number of sublineages of size < 10: 2398
Saved metadata file to david/processed/panaroo_run/sublineages_smaller_than_10.tsv