# Klebsiella metadata

In [1]:
import pandas as pd

# Load data
metadata_file = "/home/dca36/rds/rds-floto-bacterial-4k08a2yyQLw/david/final/metadata_final_curated_slimmed.tsv"
metadata = pd.read_csv(metadata_file, sep="\t")
display(metadata.head())

/tmp/ipykernel_3126711/905020374.py:5: DtypeWarning: Columns (20,133,136,138,152,153,154,155,156,160) have mixed types. Specify dtype option on import or set low_memory=False.
  metadata = pd.read_csv(metadata_file, sep="\t")

,Sample,is_kpsc,kpsc_final_list,is_refseq,is_nctc,species,species_match,Clonal group,LINcode,Phylogroup,...,year_parsed,dev_stage,scientific_name,center_name,amr_study,study_setting,bakta_gbff_downloaded,bakta_gff3_downloaded,assembly_file,gff_file
0,SAMD00002693,False,False,False,False,Klebsiella ornithinolytica,strong,NaN,NaN,NaN,...,NaN,NaN,Raoultella ornithinolytica,GIFU_MED,NaN,NaN,False,True,NaN,/home/dca36/rds/rds-floto-bacterial-4k08a2yyQL...
1,SAMD00008836,False,False,False,False,Klebsiella terrigena,strong,NaN,NaN,NaN,...,NaN,NaN,Klebsiella pneumoniae subsp. ozaenae,GIFU_MED,NaN,NaN,False,True,NaN,/home/dca36/rds/rds-floto-bacterial-4k08a2yyQL...
2,SAMD00008944,False,False,False,False,Klebsiella oxytoca,strong,NaN,NaN,NaN,...,NaN,NaN,Klebsiella oxytoca,GIFU_MED,NaN,NaN,False,True,NaN,/home/dca36/rds/rds-floto-bacterial-4k08a2yyQL...
3,SAMD00009480,False,False,False,False,Klebsiella aerogenes,strong,NaN,NaN,NaN,...,NaN,NaN,Klebsiella aerogenes,GIFU_MED,NaN,NaN,False,True,NaN,/home/dca36/rds/rds-floto-bacterial-4k08a2yyQL...
4,SAMD00049595,True,True,False,False,Klebsiella pneumoniae,strong,CG711,0_0_137_11_45_0_0_0_1_0,Kp1,...,2009.0,NaN,Klebsiella pneumoniae,KYOTO_GM,NaN,NaN,False,True,/home/dca36/rds/rds-floto-bacterial-4k08a2yyQL...,/home/dca36/rds/rds-floto-bacterial-4k08a2yyQL...

In [8]:
# Check how many gff files are missing
print(f"Number of gff files missing: {metadata['gff_file'].isna().sum()}")
missing_gff_files = metadata[metadata['gff_file'].isna()]
display(missing_gff_files.head())

Number of gff files missing: 3610

,Sample,is_kpsc,kpsc_final_list,is_refseq,is_nctc,species,species_match,Clonal group,LINcode,Phylogroup,...,year_parsed,dev_stage,scientific_name,center_name,amr_study,study_setting,bakta_gbff_downloaded,bakta_gff3_downloaded,assembly_file,gff_file
84693,GCF_020526085.1_ASM2052608v1_genomic,True,True,True,False,Klebsiella africana,strong,CG3291,4_0_3_0_0_0_0_0_0_0,Kp7,...,2016.0,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN
84694,GCF_016804125.1_ASM1680412v1_genomic,True,True,True,False,Klebsiella africana,strong,CG4938,4_0_0_0_0_0_0_0_0_0,Kp7,...,2018.0,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN
84695,GCF_023704035.1_ASM2370403v1_genomic,True,True,True,False,Klebsiella africana,strong,CG4939,4_0_1_0_0_0_0_0_0_0,Kp7,...,2018.0,NaN,NaN,NaN,NaN,NaN,False,False,NaN,NaN
84696,GCF_000764615.1_ASM76461v1_genomic,True,True,True,False,Klebsiella pneumoniae,strong,CG15,0_0_0_0_2_0_13_0_0_0,Kp1,...,2011.0,NaN,NaN,NaN,NaN,NaN,False,False,/home/dca36/rds/rds-floto-bacterial-4k08a2yyQL...,NaN
84697,GCF_000814305.1_ASM81430v1_genomic,True,True,True,False,Klebsiella pneumoniae,strong,CG258,0_0_105_6_11_0_0_0_0_0,Kp1,...,2011.0,NaN,NaN,NaN,NaN,NaN,False,False,/home/dca36/rds/rds-floto-bacterial-4k08a2yyQL...,NaN

In [10]:
# Check the assembly column completeness - 'assembly_file'
print(f"Number of metadata entries: {len(metadata)}")
print(f"Number of missing assembly files: {metadata['assembly_file'].isna().sum()}")
# Group by species and count, sort by count
missing_assembly_files = metadata[metadata['assembly_file'].isna()]
print(missing_assembly_files['species'].value_counts().head(10))

Number of metadata entries: 88303
Number of missing assembly files: 11718
species
Klebsiella variicola subsp. variicola                 3197
Klebsiella quasipneumoniae subsp. similipneumoniae    2577
Klebsiella pneumoniae                                 1557
Klebsiella quasipneumoniae subsp. quasipneumoniae     1132
Klebsiella michiganensis                               846
Klebsiella aerogenes                                   684
Klebsiella oxytoca                                     548
Klebsiella ornithinolytica                             458
Klebsiella planticola                                  215
Klebsiella grimontii                                   180
Name: count, dtype: int64

In [12]:
# Check how many are in kpsc_final_list True
missing_assembly_files_kpsc_final_list = missing_assembly_files[missing_assembly_files['kpsc_final_list']]
print(f"Number of missing assembly files in kpsc_final_list: {len(missing_assembly_files_kpsc_final_list)}")
display(missing_assembly_files_kpsc_final_list.head())

Number of missing assembly files in kpsc_final_list: 8128

,Sample,is_kpsc,kpsc_final_list,is_refseq,is_nctc,species,species_match,Clonal group,LINcode,Phylogroup,...,year_parsed,dev_stage,scientific_name,center_name,amr_study,study_setting,bakta_gbff_downloaded,bakta_gff3_downloaded,assembly_file,gff_file
20,SAMD00055727,True,True,False,False,Klebsiella pneumoniae,strong,CG10227,0_0_137_3_5_0_0_1_0_0,Kp1,...,2009.0,NaN,Klebsiella pneumoniae subsp. pneumoniae,KYOTO_GM,NaN,NaN,True,True,NaN,/home/dca36/rds/rds-floto-bacterial-4k08a2yyQL...
55,SAMD00055778,True,True,False,False,Klebsiella variicola subsp. variicola,strong,CG15452,1_0_603_1_0_0_0_0_0_0,Kp3,...,2012.0,NaN,Klebsiella variicola,KYOTO_GM,NaN,NaN,True,True,NaN,/home/dca36/rds/rds-floto-bacterial-4k08a2yyQL...
66,SAMD00055790,True,True,False,False,Klebsiella variicola subsp. variicola,strong,CG681,1_0_123_0_4_0_0_0_0_0,Kp3,...,2013.0,NaN,Klebsiella variicola,KYOTO_GM,NaN,NaN,True,True,NaN,/home/dca36/rds/rds-floto-bacterial-4k08a2yyQL...
134,SAMD00092884,True,True,False,False,Klebsiella quasipneumoniae subsp. similipneumo...,strong,CG15325,2_1_36_17_0_0_0_0_0_0,Kp4,...,2015.0,NaN,Klebsiella quasipneumoniae,KYOTO_ENG,AMR,NaN,True,True,NaN,/home/dca36/rds/rds-floto-bacterial-4k08a2yyQL...
135,SAMD00092885,True,True,False,False,Klebsiella quasipneumoniae subsp. quasipneumoniae,strong,CG14112,2_0_0_12_1_0_0_0_0_0,Kp2,...,2015.0,NaN,Klebsiella quasipneumoniae,KYOTO_ENG,AMR,NaN,True,True,NaN,/home/dca36/rds/rds-floto-bacterial-4k08a2yyQL...